### ISSUE TITLE
MRB FAIL: bulk-close-stale-mrb-boards 8be01ef013b9ea5c1b6018651375c338462a31ef

### ISSUE THREAD

**Issue by SimonBarnett** [SimonBarnett/agentic_build#170]
**Feature request:** https://github.com/SimonBarnett/agentic_build/issues/140

## Verdict
FAIL

Reviewed SHA `8be01ef013b9ea5c1b6018651375c338462a31ef` only (PR #140 head). Diff vs `docs/feature-request-pass-nits-close-finished-boards-2026-09-21.md`, `docs/build-and-test-plan-pass-nits-close-finished-boards-2026-09-21.md`, and the other parked `docs/feature-request-*.md` / `docs/build-and-test-plan*.md` on the tree. No source PDF was supplied. Shared checkout HEAD was `6805f40` on `main`; this SHA was scored from existing detached worktree `C:\ai\agentic_build-mrb-140`. Unrelated dirty files were not staged.

This SHA is `Watch-IrcTsr: recycle listen if wake log silent for 60s` (2 files: `tools/Watch-IrcTsr.ps1`, `tools/_Watch-IrcTsr-ionos.ps1`). It does not implement the chair ask. GitHub `mergeable=false` / `mergeable_state=dirty` immediately before this post. A CONFLICTING PR is FAIL even if acceptance were green in isolation: PASS-nits includes `gh pr merge`.

Prior FAIL for this same SHA: https://github.com/SimonBarnett/agentic_build/issues/165. Independently re-scored. Still red.

## Feature request
Chair of this re-review: https://github.com/SimonBarnett/agentic_build/issues/165
Product chair: https://github.com/SimonBarnett/agentic_build/issues/140 (PR #140)
Closest parked law: `docs/feature-request-pass-nits-close-finished-boards-2026-09-21.md` (issue #118, already PASS-nits via https://github.com/SimonBarnett/agentic_build/issues/139 / PR #138)
Plan: `docs/build-and-test-plan-pass-nits-close-finished-boards-2026-09-21.md`

#118 is **closed**. Its nit said historical leftover boards are **not** that FR. PR #140 is the one-shot cleanup chair and has **no** `docs/feature-request-*.md` of its own on this SHA.

PR #140 body vs this SHA:

| Ask | Result |
|---|---|
| `Close-BobMrbPassedIssues.ps1` one-shot cleanup | Script exists on the **tree** (parent commits). **This commit** does not touch it. |
| `Get-BobMrbTitleSlug` / `Get-BobMrbFeatureIssueNumbers` | On the tree in `Bob-Gh.ps1`. Not in this commit. |
| Test: live `Close-BobMrbPassedIssues.ps1 -Repo SimonBarnett/agentic_irc -WhatIf` | Not a gate. #118 acceptance 5 forbids live GitHub as the closer test. |

#118 acceptance applied to any closer that claims the PASS-nits close ritual:

1. PASS-nits merge still required. **red.** Head is CONFLICTING. This SHA does not merge anything.
2. After successful merge, FR + all prior FAIL + PASS close; each comment names the merged PR URL. **red.** `Close-BobMrbPassedIssues.ps1` comments are `Bulk close: MRB PASS-nits board (merged).`, `Superseded by MRB PASS-nits for same feature.`, `Build loop: MRB PASS-nits recorded; closing FR. Bob UAT stamp is separate.` None include a PR URL. The PASS comment claims merged with no `Test-BobGhPrIsMerged` check.
3. First-try PASS closes FR + PASS only. **red for the one-shot.** The script walks **all** `mrb` issues (limit 100), closes every open PASS, every open FAIL whose slug appears on **any** PASS (including already-closed PASS boards), and every FR listed in those bodies. That is not first-try / this-FR scoping. It also violates #118 non-goal: do not close unfinished FRs or FAIL boards that are still the live board.
4. Failed merge leaves boards open. Missing `gh.exe` is not success. **red.** Missing `gh` throws (good). The closer never checks merge state before closing or before writing (merged).
5. Test-Pack green off-DEV for the closer. No live GitHub. **red.** Official pack on this SHA: **75 pass / 0 fail**. BT118a–f score the **already-merged** loop driver (`Close-BobBuildLoopFinished`). BT119a/b score `Start-BobMrb -PrUrl`. **Zero** cases name `Close-BobMrbPassedIssues`, `Close-BobSupersededGithub`, `Merge-BobMrbPassOpenPrs`, or `Watch-IrcTsr`.
6. Loop / harvest docs point at #118. **green on main via #138.** Not this SHA's work. #140 still has no intake markdown.
7. No `PASS-UAT` from worker or driver. **green** in the reviewed files.

LOCKED: FAIL does not merge. No `password=` / `XAI_API_KEY=` assignments in this SHA.

`[Parameter(Mandatory)][string]$Repo = 'SimonBarnett/agentic_irc'` on `Close-BobMrbPassedIssues.ps1` is a live sister-repo footgun. Mandatory will prompt when unbound; the default still names the wrong repo.

## Missing features
This FR's acceptance is red. Required fixes stay on this board. No second FR for the same MUST.

Already parked, not implemented on this SHA (do not duplicate):

- https://github.com/SimonBarnett/agentic_build/issues/163 IRC TSR + Cursor listen watchdog (`docs/feature-request-watch-irc-tsr-cursor-listen-2026-09-22.md`, branch `docs/park-watch-irc-tsr-2026-09-22`, park PR https://github.com/SimonBarnett/agentic_build/pull/164). SHA `8be01ef` + parent files `Start-IrcTsr.ps1` / `Irc-Tsr-Runner.ps1` / `Watch-CursorIrc.ps1` / ionos wrappers landed with no intake. #163 AC2 already forbids idle `irc.log` mtime as a fail.
- https://github.com/SimonBarnett/agentic_build/issues/159 Ergo as Windows service BobIrcd (`docs/feature-request-ergo-windows-service-2026-09-22.md`). Not this SHA.
- https://github.com/SimonBarnett/agentic_build/issues/141 change-only webhook POST (`docs/feature-request-digest-webhook-producer-change-only-2026-09-21.md`)
- https://github.com/SimonBarnett/agentic_build/issues/124 shop-channel reportUrl (`docs/feature-request-shop-channel-worker-reporturl-2026-09-21.md`)

#118 is closed (PR #138). Its leftover-board nit is this chair, not a new FR.

No new intake filed this review. Do not implement #163 / #159 / #141 / #124 on the #140 FIX.

## Blockers
- PR #140 `mergeable=false` `mergeable_state=dirty` at head `8be01ef013b9ea5c1b6018651375c338462a31ef`. Re-read immediately before this post.
- Review SHA is Watch-IrcTsr, not the bulk-close ask.
- One-shot closer comments do not name a merged PR URL and claim merged anyway.
- No off-DEV Test-Pack for `Close-BobMrbPassedIssues`.
- No intake markdown for chair #140.

## Nits
- `Start-BobMrb.ps1` on this tree merges before `issue create` on PASS-nits (`-PrUrl`). That is fail-closed, but it is not the worker-step order on `main` and is not this SHA.
- `Close-BobSupersededGithub.ps1` / `Merge-BobMrbPassOpenPrs.ps1` can close or merge open PRs from historical `mrb-pass` bodies and issue-number title keys. Out of the PR #140 title. See required fix 8.
- Default `MachineId = 'ionos'` in `Watch-IrcTsr` / `Watch-CursorIrc` / `Start-IrcTsr`. Belongs on #163, not this FIX.
- 60s `irc.log` LastWriteTime silence recycles a healthy idle listen. Belongs on #163 AC2.
- `Watch-CursorIrc.ps1` reads `%USERPROFILE%\.grok\ergo\connect.password` from disk (path only; no assignment in git).
- Harvest log on this tree documents the TSR / hygiene pile-on. `/docs` still has no FR for #140.

## Evidence
- SHA `8be01ef013b9ea5c1b6018651375c338462a31ef`. AuthorDate 2026-09-22. `git show --stat`: 2 files, +17 / -3. Paths: `tools/Watch-IrcTsr.ps1`, `tools/_Watch-IrcTsr-ionos.ps1`. Poll 45→30, add `-SilenceSec 60`, fail healthy if wake/`irc.log` mtime ≥ 60s or missing.
- Tree vs `origin/main` (`...8be01ef`) also adds `Close-BobMrbPassedIssues.ps1`, `Close-BobSupersededGithub.ps1`, `Merge-BobMrbPassOpenPrs.ps1`, `Start-IrcTsr.ps1`, `Irc-Tsr-Runner.ps1`, `Watch-CursorIrc.ps1`, ionos wrappers, `run-bob-build-loop-irc-70-then-73.ps1`, skill/harvest edits, `Start-BobMrb -PrUrl`, `--merge` on `Invoke-BobGhMergePrIfOpen`. Those parents are on the PR; this board scores this head commit and whether the head can merge.
- Official `powershell -NoProfile -ExecutionPolicy Bypass -File C:\ai\agentic_build-mrb-140\tools\Test-Pack.ps1`: **75 pass / 0 fail**. Fake-Grok / Fake-Gh. BT118a–f PASS (loop closer, already #118). BT119a/b PASS (`-PrUrl`). No live `gh` in those cases. CI Test-Pack workflow not run (issue #15).
- `git grep` on parked `docs/feature-request-*.md` at this SHA: no `Watch-IrcTsr`, `SilenceSec`, `Close-BobMrbPassed`, `Watch-CursorIrc`.
- `gh api repos/SimonBarnett/agentic_build/pulls/140` immediately before this post: `mergeable=false`, `mergeable_state=dirty`, head `8be01ef013b9ea5c1b6018651375c338462a31ef`.
- No `password=` / `XAI_API_KEY=` assignments in this commit.

## Required fixes
1. Rebase `work/close-mrb-passed-bulk` onto current `main` until GitHub `mergeable=MERGEABLE` (not `dirty`). CONFLICTING is FAIL.
2. This head is Watch-IrcTsr. Strip from this PR: `tools/Watch-IrcTsr.ps1`, `tools/Watch-CursorIrc.ps1`, `tools/Start-IrcTsr.ps1`, `tools/Irc-Tsr-Runner.ps1`, `tools/run-bob-build-loop-irc-70-then-73.ps1`, and `_Start-IrcTsr-ionos.ps1` / `_Watch-CursorIrc-ionos.ps1` / `_Watch-IrcTsr-ionos.ps1` (and harvest-log TSR sections). Implement that surface on https://github.com/SimonBarnett/agentic_build/issues/163 only.
3. Add `docs/feature-request-bulk-close-stale-mrb-boards-2026-09-22.md` plus a build-and-test plan pointing at issue/PR #140. Chair has no intake. `/docs` must match the closer that remains on the PR.
4. Every close comment from `Close-BobMrbPassedIssues.ps1` must include the merged PR URL. Must not write merged unless that PR is merged. Current three comment strings are red.
5. Off-DEV Test-Pack for the one-shot closer: which issues close, comment contains PR URL, no close when PR still open / merge failed, missing `gh.exe` is not success. Fake-Gh only. Live `-WhatIf` against `SimonBarnett/agentic_irc` is not the gate.
6. `-Repo` on `Close-BobMrbPassedIssues.ps1` is mandatory with **no** default of `SimonBarnett/agentic_irc`.
7. Honor #118 non-goal: do not close unfinished FRs or FAIL boards that are still the live board. Slug-has-any-historical-PASS (including already-closed PASS boards) is not a sufficient gate.
8. `Close-BobSupersededGithub.ps1` / `Merge-BobMrbPassOpenPrs.ps1`: drop from this PR, **or** put them in the #140 intake with the same merge-then-comment gates and off-DEV tests. They must not close or merge live PRs for unfinished FRs.

Do not implement #163 on this FIX.

## PR
https://github.com/SimonBarnett/agentic_build/pull/140
Head `8be01ef013b9ea5c1b6018651375c338462a31ef`
FAIL. Do not merge.
